# Generated by Django 5.2.6 on 2025-09-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["user", "-created_date"], name="idx_entry_user_date_desc"),
        ),
    ]
