# Generated by Django 5.1.2 on 2025-09-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the guest",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "ordering": ["-created_date"],
            },
        ),
    ]
